apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - ../base
  - argo-postgres-config-secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
patchesStrategicMerge:
  - overlays/workflow-controller-configmap.yaml
