apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

bases:
  - ../plain
  - ../../third-party/tekton-custom-task

resources:
  - namespace.yaml

patchesStrategicMerge:
  - scheduled-workflow-crd.yaml
  - viewer-crd.yaml
