apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: metadata-grpc-service
spec:
  action: ALLOW
  selector:
    matchLabels:
      component: metadata-grpc-server
  rules:
  - {}
