apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- stateful-set.yaml
images:
- name: gcr.io/$(project)/application-controller
  newName: gcr.io/$(project)/application-controller
  newTag: latest
