apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
- ../../base
- virtual-service.yaml
namespace: kubeflow
commonLabels:
  app: tensorboards-web-app
  kustomize.component: tensorboards-web-app
configurations:
- params.yaml
